version: 1
groups:
    - annotation: sk_demo configuration
      options:

          - key: ckanext.sk_demo.option.name
            default: 10
            type: int
            description: |
                Integer placerat tristique nisl.

          - key: ckanext.sk_demo.multivalued.option
            type: list
            editable: true
            description: |
                Another option that will be parsed as a list of words.
